<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Dorado.Containers\Dorado.Containers.csproj" />
    <ProjectReference Include="..\Dorado.Xna\Dorado.Xna.csproj" />
    <ProjectReference Include="..\Dorado.Runtime\Dorado.Runtime.csproj" />
    <ProjectReference Include="..\Dorado.Platform.Desktop\Dorado.Platform.Desktop.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
