/* Generated by tools/gen_zdk_bridge.py — do not edit by hand.
 *
 * Stub definitions for the native ZDK surface the Zune XNA extension
 * P/Invokes. Hand-written files provide the real image decoder and the
 * system/font/media/cloud stubs; everything else is a silent no-op so
 * titles load and run headlessly.
 */
#include <stdint.h>
/* 145 generated exports */
#include <stddef.h>

uint32_t ZDKGL_BeginDraw(void)
{
    return 0;
}

void ZDKGL_Cleanup(void)
{
}

uint32_t ZDKGL_EndDraw(void)
{
    return 0;
}

uint32_t ZDKGL_Initialize(void)
{
    return 0;
}

void ZDKGL_glActiveTexture(uint32_t texture)
{
    (void)texture;
}

void ZDKGL_glAttachShader(uint32_t program, uint32_t shader)
{
    (void)program;
    (void)shader;
}

void ZDKGL_glBindAttribLocation(uint32_t program, uint32_t index, uint8_t* name)
{
    (void)program;
    (void)index;
    (void)name;
}

void ZDKGL_glBindBuffer(uint32_t target, uint32_t buffer)
{
    (void)target;
    (void)buffer;
}

void ZDKGL_glBindFramebuffer(uint32_t target, uint32_t framebuffer)
{
    (void)target;
    (void)framebuffer;
}

void ZDKGL_glBindRenderbuffer(uint32_t target, uint32_t renderbuffer)
{
    (void)target;
    (void)renderbuffer;
}

void ZDKGL_glBindTexture(uint32_t target, uint32_t texture)
{
    (void)target;
    (void)texture;
}

void ZDKGL_glBlendColor(float red, float green, float blue, float alpha)
{
    (void)red;
    (void)green;
    (void)blue;
    (void)alpha;
}

void ZDKGL_glBlendEquation(uint32_t mode)
{
    (void)mode;
}

void ZDKGL_glBlendEquationSeparate(uint32_t modeRGB, uint32_t modeAlpha)
{
    (void)modeRGB;
    (void)modeAlpha;
}

void ZDKGL_glBlendFunc(uint32_t sfactor, uint32_t dfactor)
{
    (void)sfactor;
    (void)dfactor;
}

void ZDKGL_glBlendFuncSeparate(uint32_t srcRGB, uint32_t dstRGB, uint32_t srcAlpha, uint32_t dstAlpha)
{
    (void)srcRGB;
    (void)dstRGB;
    (void)srcAlpha;
    (void)dstAlpha;
}

uint32_t ZDKGL_glBufferData(uint32_t target, int32_t size, void* data, uint32_t usage)
{
    (void)target;
    (void)size;
    (void)data;
    (void)usage;
    return 0;
}

void ZDKGL_glBufferSubData(uint32_t target, int32_t offset, int32_t size, void* data)
{
    (void)target;
    (void)offset;
    (void)size;
    (void)data;
}

uint32_t ZDKGL_glCheckFramebufferStatus(uint32_t target)
{
    (void)target;
    return 0;
}

void ZDKGL_glClear(uint32_t mask)
{
    (void)mask;
}

void ZDKGL_glClearColor(float red, float green, float blue, float alpha)
{
    (void)red;
    (void)green;
    (void)blue;
    (void)alpha;
}

void ZDKGL_glClearDepthf(float depth)
{
    (void)depth;
}

void ZDKGL_glClearStencil(int32_t s)
{
    (void)s;
}

void ZDKGL_glColorMask(uint32_t red, uint32_t green, uint32_t blue, uint32_t alpha)
{
    (void)red;
    (void)green;
    (void)blue;
    (void)alpha;
}

uint32_t ZDKGL_glCompressedTexImage2D(uint32_t target, int32_t level, uint32_t internalformat, int32_t width, int32_t height, int32_t border, int32_t imageSize, uint8_t* data)
{
    (void)target;
    (void)level;
    (void)internalformat;
    (void)width;
    (void)height;
    (void)border;
    (void)imageSize;
    (void)data;
    return 0;
}

void ZDKGL_glCompressedTexSubImage2D(uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t width, int32_t height, uint32_t format, int32_t imageSize, void* data)
{
    (void)target;
    (void)level;
    (void)xoffset;
    (void)yoffset;
    (void)width;
    (void)height;
    (void)format;
    (void)imageSize;
    (void)data;
}

void ZDKGL_glCopyTexImage2D(uint32_t target, int32_t level, uint32_t internalformat, int32_t x, int32_t y, int32_t width, int32_t height, int32_t border)
{
    (void)target;
    (void)level;
    (void)internalformat;
    (void)x;
    (void)y;
    (void)width;
    (void)height;
    (void)border;
}

void ZDKGL_glCopyTexSubImage2D(uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t x, int32_t y, int32_t width, int32_t height)
{
    (void)target;
    (void)level;
    (void)xoffset;
    (void)yoffset;
    (void)x;
    (void)y;
    (void)width;
    (void)height;
}

uint32_t ZDKGL_glCreateProgram(void)
{
    return 0;
}

uint32_t ZDKGL_glCreateShader(uint32_t type)
{
    (void)type;
    return 0;
}

void ZDKGL_glCullFace(uint32_t mode)
{
    (void)mode;
}

void ZDKGL_glDeleteBuffers(int32_t n, uint8_t* buffers)
{
    (void)n;
    (void)buffers;
}

void ZDKGL_glDeleteFramebuffers(int32_t n, uint8_t* framebuffers)
{
    (void)n;
    (void)framebuffers;
}

void ZDKGL_glDeleteProgram(uint32_t program)
{
    (void)program;
}

void ZDKGL_glDeleteRenderbuffers(int32_t n, uint8_t* renderbuffers)
{
    (void)n;
    (void)renderbuffers;
}

void ZDKGL_glDeleteShader(uint32_t shader)
{
    (void)shader;
}

void ZDKGL_glDeleteTextures(int32_t n, uint8_t* textures)
{
    (void)n;
    (void)textures;
}

void ZDKGL_glDepthFunc(uint32_t func)
{
    (void)func;
}

void ZDKGL_glDepthMask(uint32_t flag)
{
    (void)flag;
}

void ZDKGL_glDepthRangef(float zNear, float zFar)
{
    (void)zNear;
    (void)zFar;
}

void ZDKGL_glDetachShader(uint32_t program, uint32_t shader)
{
    (void)program;
    (void)shader;
}

void ZDKGL_glDisable(uint32_t cap)
{
    (void)cap;
}

void ZDKGL_glDisableVertexAttribArray(uint32_t index)
{
    (void)index;
}

void ZDKGL_glDrawArrays(uint32_t mode, int32_t first, int32_t count)
{
    (void)mode;
    (void)first;
    (void)count;
}

void ZDKGL_glDrawElements(uint32_t mode, int32_t count, uint32_t type, void* indices)
{
    (void)mode;
    (void)count;
    (void)type;
    (void)indices;
}

void ZDKGL_glDrawRangeElements(uint32_t mode, uint32_t start, uint32_t end, int32_t count, uint32_t type, void* indices)
{
    (void)mode;
    (void)start;
    (void)end;
    (void)count;
    (void)type;
    (void)indices;
}

void ZDKGL_glEnable(uint32_t cap)
{
    (void)cap;
}

void ZDKGL_glEnableVertexAttribArray(uint32_t index)
{
    (void)index;
}

void ZDKGL_glFinish(void)
{
}

void ZDKGL_glFlush(void)
{
}

void ZDKGL_glFramebufferRenderbuffer(uint32_t target, uint32_t attachment, uint32_t renderbuffertarget, uint32_t renderbuffer)
{
    (void)target;
    (void)attachment;
    (void)renderbuffertarget;
    (void)renderbuffer;
}

void ZDKGL_glFramebufferTexture2D(uint32_t target, uint32_t attachment, uint32_t textarget, uint32_t texture, int32_t level)
{
    (void)target;
    (void)attachment;
    (void)textarget;
    (void)texture;
    (void)level;
}

void ZDKGL_glFrontFace(uint32_t mode)
{
    (void)mode;
}

void ZDKGL_glGenBuffers(int32_t n, uint8_t* buffers)
{
    (void)n;
    (void)buffers;
}

void ZDKGL_glGenFramebuffers(int32_t n, uint8_t* framebuffers)
{
    (void)n;
    (void)framebuffers;
}

void ZDKGL_glGenRenderbuffers(int32_t n, uint8_t* renderbuffers)
{
    (void)n;
    (void)renderbuffers;
}

void ZDKGL_glGenTextures(int32_t n, uint8_t* textures)
{
    (void)n;
    (void)textures;
}

uint32_t ZDKGL_glGenerateMipmap(uint32_t target)
{
    (void)target;
    return 0;
}

void ZDKGL_glGetActiveAttrib(uint32_t program, uint32_t index, int32_t bufsize, int32_t* length, int32_t* size, uint32_t* type, uint8_t* name)
{
    (void)program;
    (void)index;
    (void)bufsize;
    if (length) *length = 0;
    if (size) *size = 0;
    if (type) *type = 0;
    (void)name;
}

void ZDKGL_glGetActiveUniform(uint32_t program, uint32_t index, int32_t bufsize, int32_t* length, int32_t* size, uint32_t* type, uint8_t* name)
{
    (void)program;
    (void)index;
    (void)bufsize;
    if (length) *length = 0;
    if (size) *size = 0;
    if (type) *type = 0;
    (void)name;
}

void ZDKGL_glGetAttachedShaders(uint32_t program, int32_t maxcount, int32_t* count, uint8_t* shaders)
{
    (void)program;
    (void)maxcount;
    if (count) *count = 0;
    (void)shaders;
}

int32_t ZDKGL_glGetAttribLocation(uint32_t program, uint8_t* name)
{
    (void)program;
    (void)name;
    return 0;
}

void ZDKGL_glGetBooleanv(uint32_t pname, uint8_t* parms)
{
    (void)pname;
    (void)parms;
}

void ZDKGL_glGetBufferParameteriv(uint32_t target, uint32_t pname, int32_t* parms)
{
    (void)target;
    (void)pname;
    if (parms) *parms = 0;
}

uint32_t ZDKGL_glGetError(void)
{
    return 0;
}

void ZDKGL_glGetFloatv(uint32_t pname, float* parms)
{
    (void)pname;
    (void)parms;
}

void ZDKGL_glGetFramebufferAttachmentParameteriv(uint32_t target, uint32_t attachment, uint32_t pname, int32_t* parms)
{
    (void)target;
    (void)attachment;
    (void)pname;
    if (parms) *parms = 0;
}

void ZDKGL_glGetIntegerv(uint32_t pname, uint8_t* parms)
{
    (void)pname;
    (void)parms;
}

void ZDKGL_glGetProgramInfoLog(uint32_t program, int32_t bufsize, int32_t* length, uint8_t* infolog)
{
    (void)program;
    (void)bufsize;
    if (length) *length = 0;
    (void)infolog;
}

void ZDKGL_glGetProgramiv(uint32_t program, uint32_t pname, int32_t* parms)
{
    (void)program;
    (void)pname;
    if (parms) *parms = 0;
}

void ZDKGL_glGetRenderbufferParameteriv(uint32_t target, uint32_t pname, int32_t* parms)
{
    (void)target;
    (void)pname;
    if (parms) *parms = 0;
}

void ZDKGL_glGetShaderInfoLog(uint32_t shader, int32_t bufsize, int32_t* length, uint8_t* infolog)
{
    (void)shader;
    (void)bufsize;
    if (length) *length = 0;
    (void)infolog;
}

void ZDKGL_glGetShaderPrecisionFormat(uint32_t shadertype, uint32_t precisiontype, int32_t* range, int32_t* precision)
{
    (void)shadertype;
    (void)precisiontype;
    if (range) *range = 0;
    if (precision) *precision = 0;
}

void ZDKGL_glGetShaderiv(uint32_t shader, uint32_t pname, int32_t* parms)
{
    (void)shader;
    (void)pname;
    if (parms) *parms = 0;
}

void ZDKGL_glGetString(uint32_t name, int32_t bufsize, int32_t* length, uint8_t* str)
{
    (void)name;
    (void)bufsize;
    if (length) *length = 0;
    (void)str;
}

void ZDKGL_glGetTexParameterfv(uint32_t target, uint32_t pname, float* parms)
{
    (void)target;
    (void)pname;
    if (parms) *parms = 0;
}

void ZDKGL_glGetTexParameteriv(uint32_t target, uint32_t pname, int32_t* parms)
{
    (void)target;
    (void)pname;
    if (parms) *parms = 0;
}

int32_t ZDKGL_glGetUniformLocation(uint32_t program, uint8_t* name)
{
    (void)program;
    (void)name;
    return 0;
}

void ZDKGL_glGetUniformfv(uint32_t program, int32_t location, float* parms)
{
    (void)program;
    (void)location;
    (void)parms;
}

void ZDKGL_glGetUniformiv(uint32_t program, int32_t location, uint8_t* parms)
{
    (void)program;
    (void)location;
    (void)parms;
}

void ZDKGL_glGetVertexAttribfv(uint32_t index, uint32_t pname, float* parms)
{
    (void)index;
    (void)pname;
    if (parms) *parms = 0;
}

void ZDKGL_glGetVertexAttribiv(uint32_t index, uint32_t pname, int32_t* parms)
{
    (void)index;
    (void)pname;
    if (parms) *parms = 0;
}

void ZDKGL_glHint(uint32_t target, uint32_t mode)
{
    (void)target;
    (void)mode;
}

uint32_t ZDKGL_glIsBuffer(uint32_t buffer)
{
    (void)buffer;
    return 0;
}

uint32_t ZDKGL_glIsEnabled(uint32_t cap)
{
    (void)cap;
    return 0;
}

uint32_t ZDKGL_glIsFramebuffer(uint32_t framebuffer)
{
    (void)framebuffer;
    return 0;
}

uint32_t ZDKGL_glIsProgram(uint32_t program)
{
    (void)program;
    return 0;
}

uint32_t ZDKGL_glIsRenderbuffer(uint32_t renderbuffer)
{
    (void)renderbuffer;
    return 0;
}

uint32_t ZDKGL_glIsShader(uint32_t shader)
{
    (void)shader;
    return 0;
}

uint32_t ZDKGL_glIsTexture(uint32_t texture)
{
    (void)texture;
    return 0;
}

void ZDKGL_glLineWidth(float width)
{
    (void)width;
}

void ZDKGL_glLinkProgram(uint32_t program)
{
    (void)program;
}

void ZDKGL_glPixelStorei(uint32_t pname, int32_t param)
{
    (void)pname;
    (void)param;
}

void ZDKGL_glPolygonOffset(float factor, float units)
{
    (void)factor;
    (void)units;
}

void ZDKGL_glReadPixels(int32_t x, int32_t y, int32_t width, int32_t height, uint32_t format, uint32_t type, void* pixels)
{
    (void)x;
    (void)y;
    (void)width;
    (void)height;
    (void)format;
    (void)type;
    (void)pixels;
}

uint32_t ZDKGL_glRenderbufferStorage(uint32_t target, uint32_t internalformat, int32_t width, int32_t height)
{
    (void)target;
    (void)internalformat;
    (void)width;
    (void)height;
    return 0;
}

void ZDKGL_glSampleCoverage(float value, uint32_t invert)
{
    (void)value;
    (void)invert;
}

void ZDKGL_glScissor(int32_t x, int32_t y, int32_t width, int32_t height)
{
    (void)x;
    (void)y;
    (void)width;
    (void)height;
}

void ZDKGL_glShaderBinary(int32_t n, void* shaders, uint32_t binaryformat, uint8_t* binary, int32_t length)
{
    (void)n;
    (void)shaders;
    (void)binaryformat;
    (void)binary;
    (void)length;
}

void ZDKGL_glStencilFunc(uint32_t func, int32_t reference, uint32_t mask)
{
    (void)func;
    (void)reference;
    (void)mask;
}

void ZDKGL_glStencilFuncSeparate(uint32_t face, uint32_t func, int32_t reference, uint32_t mask)
{
    (void)face;
    (void)func;
    (void)reference;
    (void)mask;
}

void ZDKGL_glStencilMask(uint32_t mask)
{
    (void)mask;
}

void ZDKGL_glStencilMaskSeparate(uint32_t face, uint32_t mask)
{
    (void)face;
    (void)mask;
}

void ZDKGL_glStencilOp(uint32_t fail, uint32_t zfail, uint32_t zpass)
{
    (void)fail;
    (void)zfail;
    (void)zpass;
}

void ZDKGL_glStencilOpSeparate(uint32_t face, uint32_t fail, uint32_t zfail, uint32_t zpass)
{
    (void)face;
    (void)fail;
    (void)zfail;
    (void)zpass;
}

uint32_t ZDKGL_glTexImage2D(uint32_t target, int32_t level, uint32_t internalformat, int32_t width, int32_t height, int32_t border, uint32_t format, uint32_t type, uint8_t* pixels)
{
    (void)target;
    (void)level;
    (void)internalformat;
    (void)width;
    (void)height;
    (void)border;
    (void)format;
    (void)type;
    (void)pixels;
    return 0;
}

void ZDKGL_glTexParameterf(uint32_t target, uint32_t pname, float param)
{
    (void)target;
    (void)pname;
    (void)param;
}

void ZDKGL_glTexParameterfv(uint32_t target, uint32_t pname, float* parms)
{
    (void)target;
    (void)pname;
    (void)parms;
}

void ZDKGL_glTexParameteri(uint32_t target, uint32_t pname, int32_t param)
{
    (void)target;
    (void)pname;
    (void)param;
}

void ZDKGL_glTexParameteriv(uint32_t target, uint32_t pname, uint8_t* parms)
{
    (void)target;
    (void)pname;
    (void)parms;
}

void ZDKGL_glTexSubImage2D(uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t width, int32_t height, uint32_t format, uint32_t type, uint8_t* pixels)
{
    (void)target;
    (void)level;
    (void)xoffset;
    (void)yoffset;
    (void)width;
    (void)height;
    (void)format;
    (void)type;
    (void)pixels;
}

void ZDKGL_glUniform1f(int32_t location, float x)
{
    (void)location;
    (void)x;
}

void ZDKGL_glUniform1fv(int32_t location, int32_t count, float* v)
{
    (void)location;
    (void)count;
    (void)v;
}

void ZDKGL_glUniform1i(int32_t location, int32_t x)
{
    (void)location;
    (void)x;
}

void ZDKGL_glUniform1iv(int32_t location, int32_t count, uint8_t* v)
{
    (void)location;
    (void)count;
    (void)v;
}

void ZDKGL_glUniform2f(int32_t location, float x, float y)
{
    (void)location;
    (void)x;
    (void)y;
}

void ZDKGL_glUniform2fv(int32_t location, int32_t count, float* v)
{
    (void)location;
    (void)count;
    (void)v;
}

void ZDKGL_glUniform2i(int32_t location, int32_t x, int32_t y)
{
    (void)location;
    (void)x;
    (void)y;
}

void ZDKGL_glUniform2iv(int32_t location, int32_t count, uint8_t* v)
{
    (void)location;
    (void)count;
    (void)v;
}

void ZDKGL_glUniform3f(int32_t location, float x, float y, float z)
{
    (void)location;
    (void)x;
    (void)y;
    (void)z;
}

void ZDKGL_glUniform3fv(int32_t location, int32_t count, float* v)
{
    (void)location;
    (void)count;
    (void)v;
}

void ZDKGL_glUniform3i(int32_t location, int32_t x, int32_t y, int32_t z)
{
    (void)location;
    (void)x;
    (void)y;
    (void)z;
}

void ZDKGL_glUniform3iv(int32_t location, int32_t count, uint8_t* v)
{
    (void)location;
    (void)count;
    (void)v;
}

void ZDKGL_glUniform4f(int32_t location, float x, float y, float z, float w)
{
    (void)location;
    (void)x;
    (void)y;
    (void)z;
    (void)w;
}

void ZDKGL_glUniform4fv(int32_t location, int32_t count, float* v)
{
    (void)location;
    (void)count;
    (void)v;
}

void ZDKGL_glUniform4i(int32_t location, int32_t x, int32_t y, int32_t z, int32_t w)
{
    (void)location;
    (void)x;
    (void)y;
    (void)z;
    (void)w;
}

void ZDKGL_glUniform4iv(int32_t location, int32_t count, uint8_t* v)
{
    (void)location;
    (void)count;
    (void)v;
}

void ZDKGL_glUniformMatrix2fv(int32_t location, int32_t count, uint32_t transpose, float* value)
{
    (void)location;
    (void)count;
    (void)transpose;
    (void)value;
}

void ZDKGL_glUniformMatrix3fv(int32_t location, int32_t count, uint32_t transpose, float* value)
{
    (void)location;
    (void)count;
    (void)transpose;
    (void)value;
}

void ZDKGL_glUniformMatrix4fv(int32_t location, int32_t count, uint32_t transpose, float* value)
{
    (void)location;
    (void)count;
    (void)transpose;
    (void)value;
}

void ZDKGL_glUseProgram(uint32_t program)
{
    (void)program;
}

void ZDKGL_glValidateProgram(uint32_t program)
{
    (void)program;
}

void ZDKGL_glVertexAttrib1f(uint32_t indx, float x)
{
    (void)indx;
    (void)x;
}

void ZDKGL_glVertexAttrib1fv(uint32_t indx, float* values)
{
    (void)indx;
    (void)values;
}

void ZDKGL_glVertexAttrib2f(uint32_t indx, float x, float y)
{
    (void)indx;
    (void)x;
    (void)y;
}

void ZDKGL_glVertexAttrib2fv(uint32_t indx, float* values)
{
    (void)indx;
    (void)values;
}

void ZDKGL_glVertexAttrib3f(uint32_t indx, float x, float y, float z)
{
    (void)indx;
    (void)x;
    (void)y;
    (void)z;
}

void ZDKGL_glVertexAttrib3fv(uint32_t indx, float* values)
{
    (void)indx;
    (void)values;
}

void ZDKGL_glVertexAttrib4f(uint32_t indx, float x, float y, float z, float w)
{
    (void)indx;
    (void)x;
    (void)y;
    (void)z;
    (void)w;
}

void ZDKGL_glVertexAttrib4fv(uint32_t indx, float* values)
{
    (void)indx;
    (void)values;
}

void ZDKGL_glVertexAttribPointer(uint32_t indx, int32_t size, uint32_t type, uint32_t normalized, int32_t stride, void* ptr)
{
    (void)indx;
    (void)size;
    (void)type;
    (void)normalized;
    (void)stride;
    (void)ptr;
}

void ZDKGL_glVertexAttribPointerEx(uint32_t cVertexAttrib, uint8_t* pVertexAttrib)
{
    (void)cVertexAttrib;
    (void)pVertexAttrib;
}

void ZDKGL_glViewport(int32_t x, int32_t y, int32_t width, int32_t height)
{
    (void)x;
    (void)y;
    (void)width;
    (void)height;
}

uint32_t ZDKInput_EnableInputMessages(int32_t fEnable)
{
    (void)fEnable;
    return 0;
}

uint32_t ZDKInput_GetNextInputMessage(void** msg)
{
    if (msg) *msg = 0;
    return 0;
}
